In [54]:
#check for inconsistency
import pandas as pd
import numpy as np
import fuzzywuzzy as fw
from fuzzywuzzy import process
import chardet as cd

1. fuzzywuzzy

The fuzzywuzzy library is used for string matching and approximate string matching. It is commonly used to find similarities between strings and perform fuzzy searching.

Use Cases:
	•	Finding Similar Strings: Calculate the similarity ratio between two strings.
	•	String Matching: Find the closest match from a list of strings.
	•	Data Cleaning: Identify and group similar entries in datasets.

Key Functions:
	•	fuzzywuzzy.fuzz.ratio(string1, string2): Computes the similarity ratio between two strings (0–100 scale).
	•	fuzzywuzzy.fuzz.partial_ratio(string1, string2): Computes similarity for substrings.
	•	fuzzywuzzy.fuzz.token_sort_ratio(string1, string2): Ignores word order while matching.
	•	fuzzywuzzy.process.extract(query, choices): Finds the closest matches for a query in a list of choices.

Example:

In [56]:
from fuzzywuzzy import fuzz, process

# Similarity ratio
print(fuzz.ratio("apple", "apples"))  # Output: 91

# Find the closest match
choices = ["apple", "banana", "grape"]
query = "appel"
print(process.extractOne(query, choices))  # Output: ('apple', 80)

91
('apple', 80)

In [57]:
import chardet as cd
with open("//Users//vanshpahwa//Downloads//PakistanSuicideAttacks Ver 11 (30-November-2017).csv", 'rb') as rawdata:
    result = cd.detect(rawdata.read(100000))

# check what the character encoding might be
print(result)

{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}

In [58]:
df = pd.read_csv("//Users//vanshpahwa//Downloads//PakistanSuicideAttacks Ver 11 (30-November-2017).csv", 
                              encoding='Windows-1252')
df

,S#,Date,Islamic Date,Blast Day Type,Holiday Type,Time,City,Latitude,Longitude,Province,...,Targeted Sect if any,Killed Min,Killed Max,Injured Min,Injured Max,No. of Suicide Blasts,Explosive Weight (max),Hospital Names,Temperature(C),Temperature(F)
0,1,Sunday-November 19-1995,25 Jumaada al-THaany 1416 A.H,Holiday,Weekend,NaN,Islamabad,33.718000,73.0718,Capital,...,NaN,14.0,15.0,NaN,60,2.0,NaN,NaN,15.835,60.503
1,2,Monday-November 6-2000,10 SHa`baan 1421 A.H,Working Day,NaN,NaN,Karachi,24.991800,66.9911,Sindh,...,NaN,NaN,3.0,NaN,3,1.0,NaN,NaN,23.770,74.786
2,3,Wednesday-May 8-2002,25 safar 1423 A.H,Working Day,NaN,7:45 AM,Karachi,24.991800,66.9911,Sindh,...,Christian,13.0,15.0,20.0,40,1.0,2.5 Kg,1.Jinnah Postgraduate Medical Center 2. Civil ...,31.460,88.628
3,4,Friday-June 14-2002,3 Raby` al-THaany 1423 A.H,Working Day,NaN,11:10:00 AM,Karachi,24.991800,66.9911,Sindh,...,Christian,NaN,12.0,NaN,51,1.0,NaN,NaN,31.430,88.574
4,5,Friday-July 4-2003,4 Jumaada al-awal 1424 A.H,Working Day,NaN,NaN,Quetta,30.209500,67.0182,Baluchistan,...,Shiite,44.0,47.0,NaN,65,1.0,NaN,1.CMH Quetta \n2.Civil Hospital 3. Boland Medi...,33.120,91.616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,492,Thursday-October-05-2017,13 MuHarram 1439 A.H,Working Day,NaN,NaN,Quetta,28.571051,67.496895,Balochistan,...,NaN,21.0,22.0,25.0,NaN,1.0,NaN,"Larkana Hospital, Gandawah District Headquarte...",27.800,81.000
492,493,Thursday-October-19-2017,27 MuHarram 1439 A.H,Working Day,NaN,8:00 AM,Quetta,NaN,NaN,Balochistan,...,NaN,7.0,7.0,22.0,22,1.0,NaN,NaN,26.000,79.000
493,494,Thursday-November-9-2017,19 Safar 1439 A.H,Working Day,NaN,7:00 AM,Quetta,30.221057,67.002524,Balochistan,...,NaN,2.0,2.0,8.0,8,1.0,15KG,"Combined Military Hospital (CMH)-(Quetta), Civ...",25.000,77.000
494,495,Friday-November-24-2017,5 Rabi Al-Awwal 1439 A.H,Working Day,NaN,7:00 AM,Peshawar,33.970623,71.43862,KPK,...,NaN,1.0,3.0,6.0,8,1.0,20KG,Hayatabad Medical Complex(Peshawar),22.000,72.000
495,496,Saturday-November-25-2017,6 Rabi Al-Awwal 1439 A.H,Working Day,NaN,7:00 AM,Quetta,30.139626,66.981476,Balochistan,...,NaN,4.0,4.0,16.0,22,1.0,10KG,Civil Hospital(Quetta),29.000,84.000

In [59]:
# get all the unique values in the 'City' column
cities = df['City'].unique()

# sort them alphabetically and then take a closer look
cities.sort()
cities

array(['ATTOCK', 'Attock ', 'Bajaur Agency', 'Bannu', 'Bhakkar ', 'Buner',
       'Chakwal ', 'Chaman', 'Charsadda', 'Charsadda ', 'D. I Khan',
       'D.G Khan', 'D.G Khan ', 'D.I Khan', 'D.I Khan ', 'Dara Adam Khel',
       'Dara Adam khel', 'Fateh Jang', 'Ghallanai, Mohmand Agency ',
       'Gujrat', 'Hangu', 'Haripur', 'Hayatabad', 'Islamabad',
       'Islamabad ', 'Jacobabad', 'KURRAM AGENCY', 'Karachi', 'Karachi ',
       'Karak', 'Khanewal', 'Khuzdar', 'Khyber Agency', 'Khyber Agency ',
       'Kohat', 'Kohat ', 'Kuram Agency ', 'Lahore', 'Lahore ',
       'Lakki Marwat', 'Lakki marwat', 'Lasbela', 'Lower Dir', 'MULTAN',
       'Malakand ', 'Mansehra', 'Mardan', 'Mohmand Agency',
       'Mohmand Agency ', 'Mohmand agency', 'Mosal Kor, Mohmand Agency',
       'Multan', 'Muzaffarabad', 'North Waziristan', 'North waziristan',
       'Nowshehra', 'Orakzai Agency', 'Peshawar', 'Peshawar ', 'Pishin',
       'Poonch', 'Quetta', 'Quetta ', 'Rawalpindi', 'Sargodha',
       'Sehwan town', 'Shabqadar-Charsadda', 'Shangla ', 'Shikarpur',
       'Sialkot', 'South Waziristan', 'South waziristan', 'Sudhanoti',
       'Sukkur', 'Swabi ', 'Swat', 'Swat ', 'Taftan',
       'Tangi, Charsadda District', 'Tank', 'Tank ', 'Taunsa',
       'Tirah Valley', 'Totalai', 'Upper Dir', 'Wagah', 'Zhob', 'bannu',
       'karachi', 'karachi ', 'lakki marwat', 'peshawar', 'swat'],
      dtype=object)

In [106]:
#convert to lower case
df['City'] = df['City'].str.lower()
# remove trailing white spaces
df['City'] = df['City'].str.strip()
import fuzzywuzzy
# get the top 10 closest matches to "d.i khan"
matches = fuzzywuzzy.process.extract("d.i khan", cities, limit=10, scorer=fuzzywuzzy.fuzz.token_sort_ratio)
# take a look at them
matches
def replace_matches_in_column(d_f, column, string_to_match, min_ratio = 90):
    # get a list of unique strings
    strings = df[column].unique()
    
    # get the top 10 closest matches to our input string
    matches = fuzzywuzzy.process.extract(string_to_match, strings, 
                                         limit=10, scorer=fuzzywuzzy.fuzz.token_sort_ratio)

    # only get matches with a ratio > 90
    close_matches = [matches[0] for matches in matches if matches[1] >= min_ratio]

    # get the rows of all the close matches in our dataframe
    rows_with_matches = df[column].isin(close_matches)

    # replace all rows with close matches with the input matches 
    df.loc[rows_with_matches, column] = string_to_match
    
    # let us know the function's done
    print("All done!")
replace_matches_in_column(d_f=df, column='City', string_to_match="d.i khan")
# get all the unique values in the 'City' column
cities = df['City'].unique()

# sort them alphabetically and then take a closer look
cities.sort()
cities
df['City'] = df['City'].str.lower()
df['City'] = df['City'].str.strip()
cities

All done!

array(['attock', 'bajaur agency', 'bannu', 'bhakkar', 'buner', 'chakwal',
       'chaman', 'charsadda', 'd.g khan', 'd.i khan', 'dara adam khel',
       'fateh jang', 'ghallanai, mohmand agency', 'gujrat', 'hangu',
       'haripur', 'hayatabad', 'islamabad', 'jacobabad', 'karachi',
       'karak', 'khanewal', 'khuzdar', 'khyber agency', 'kohat',
       'kuram agency', 'kurram agency', 'lahore', 'lakki marwat',
       'lasbela', 'lower dir', 'malakand', 'mansehra', 'mardan',
       'mohmand agency', 'mosal kor, mohmand agency', 'multan',
       'muzaffarabad', 'north waziristan', 'nowshehra', 'orakzai agency',
       'peshawar', 'pishin', 'poonch', 'quetta', 'rawalpindi', 'sargodha',
       'sehwan town', 'shabqadar-charsadda', 'shangla', 'shikarpur',
       'sialkot', 'south waziristan', 'sudhanoti', 'sukkur', 'swabi',
       'swat', 'taftan', 'tangi, charsadda district', 'tank', 'taunsa',
       'tirah valley', 'totalai', 'upper dir', 'wagah', 'zhob'],
      dtype=object)